name: transia_mobile
description: "Application mobile Transia pour la réservation de billets de bus interurbain."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.4

  share_plus: ^10.0.2

  cupertino_icons: ^1.0.8

  # Navigation
  go_router: ^14.8.1

  # API HTTP
  dio: ^5.8.0+1

  # Gestion d'état
  provider: ^6.1.2

  # Stockage local et sécurisé
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.4.1
  path: ^1.9.1

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.6

  # Sélection de photo (profil)
  image_picker: ^1.1.2

  # GPS / Maps
  geolocator: ^13.0.2
  geocoding: ^5.0.0
  url_launcher: ^6.3.1
  # google_maps_flutter: ^2.10.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # UI / Formatage
  google_fonts: ^6.2.1
  intl: ^0.20.2
  pdf: ^3.12.0
  printing: ^5.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/